"""
paper_runner.py — Daily Operator for RS60/EP40 Paper Trading
=============================================================
Run this script each morning BEFORE 9:15 AM IST.

What it does:
  1. Reads today's ops log (generated by daily_ops_report.py)
  2. Prints EXACT orders to place / cancel at market open
  3. Logs all actions to paper_runner.log

Usage:
  python paper_runner.py          (reads today's ops log)
  python paper_runner.py --run    (also re-runs daily_ops_report.py first)

This script does NOT place real orders. It tells you what to do manually.
"""

import json
import sys
import logging
from datetime import date
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [PAPER_RUNNER] %(message)s",
    handlers=[
        logging.FileHandler("paper_runner.log", encoding="utf-8"),
        logging.StreamHandler(sys.stdout)
    ]
)
log = logging.getLogger(__name__)

TODAY = str(date.today())
OPS_LOG = Path(f"ops_log_{TODAY}.json")


def load_ops_log(path: Path) -> dict:
    if not path.exists():
        log.error(f"Ops log not found: {path}")
        log.error("Run: python daily_ops_report.py   first.")
        sys.exit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def print_orders(ops: dict):
    sep = "=" * 60
    print(f"\n{sep}")
    print(f"  RS60/EP40 PAPER TRADING — {TODAY}")
    print(sep)

    regime = ops.get("regime", "UNKNOWN")
    nifty  = ops.get("nifty", ops.get("nifty_close", 0))
    dma200 = ops.get("dma200", 0)

    print(f"\n  REGIME    : {regime}")
    print(f"  Nifty     : {nifty:,.2f}  |  200-DMA: {dma200:,.2f}")

    if regime == "BEAR":
        print("\n  *** BEAR REGIME — HOLD 100% CASH. DO NOT TRADE. ***")
        print(f"  Nifty ({nifty:,.0f}) is BELOW 200-DMA ({dma200:,.0f}).")
        print("  Exit any open positions at today's market open (T+1 open fill).")

        exits = ops.get("regime_exits", [])
        if exits:
            print(f"\n  REGIME EXIT ORDERS (sell at market open):")
            for e in exits:
                print(f"    SELL  {e['symbol']:15s}  qty={e.get('qty', '?')}  reason=Regime EXIT")
        else:
            print("\n  No open positions to exit.")

    elif regime in ("BULL", "FLAT"):
        rebalance_due = ops.get("rebalance_due", False)
        print(f"\n  Rebalance due: {'YES' if rebalance_due else 'NO'}")

        if rebalance_due:
            buys  = ops.get("buys",  [])
            sells = ops.get("sells", [])

            if sells:
                print(f"\n  SELL ORDERS (place at market open):")
                for s in sells:
                    print(f"    SELL  {s['symbol']:15s}  qty={s.get('qty', '?')}")

            if buys:
                print(f"\n  BUY ORDERS (place at market open):")
                for b in buys:
                    print(f"    BUY   {b['symbol']:15s}  alloc=Rs.{b.get('alloc_rs', '?'):.0f}")

            if not buys and not sells:
                print("\n  No changes to portfolio today.")
        else:
            print("\n  No rebalance today. Monitor open positions for stop-loss hits.")

        sl_hits = ops.get("sl_hits", [])
        if sl_hits:
            print(f"\n  STOP-LOSS ALERTS (sell at TODAY close if not already done):")
            for s in sl_hits:
                print(f"    SL    {s['symbol']:15s}  entry={s.get('entry',0):.2f}  sl_price={s.get('sl_price',0):.2f}  close={s.get('close',0):.2f}")

    print(f"\n{sep}\n")


def main():
    run_report = "--run" in sys.argv
    if run_report:
        log.info("Running daily_ops_report.py first...")
        import subprocess
        result = subprocess.run(
            [sys.executable, "daily_ops_report.py"],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            log.error(f"daily_ops_report.py failed:\n{result.stderr}")
            sys.exit(1)
        log.info("daily_ops_report.py completed.")

    ops = load_ops_log(OPS_LOG)
    print_orders(ops)
    log.info(f"paper_runner done. Regime={ops.get('regime','?')}  Nifty={ops.get('nifty', ops.get('nifty_close','?'))}")


if __name__ == "__main__":
    main()
